FROM node:13.7.0-alpine as builder

EXPOSE 3000

RUN mkdir /app
WORKDIR /app
RUN yarn global add pm2
COPY ./web/package.json ./web/yarn.lock ./
RUN yarn install
COPY ./web ./

FROM builder as production
RUN yarn build
CMD [ "pm2-runtime", "start", "yarn", "--", "start" ]

FROM builder as development
CMD [ "yarn", "dev" ]
